services:
  - type: web
    name: medbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && waitress-serve --host=0.0.0.0 --port=$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 